### ISSUE TITLE
Footer - layout not correct

### ISSUE THREAD

**Issue by luciaV86** [lifewatch-eric/ecoportal_web_ui#112]
The footer should respect the LifeWatch ERIC one (see how it is implemented in the current version of EcoPortal) i.e. a **unique row** having as columns: logo, Products, Support, Disclaimers & Agreements, About, Social icons.

**Comment by syphax-bouazzouni** [comment]
Hello @luciaV86, 
Do you think this is a must-have or a blocker? I mention this because the current footer is the version agreed upon by the OntoPortal Alliance, a merged version of the old EcoPortal and AgroPortal footers.

If so, I can revert to the old footer, but doing so may make it harder to align with others in the future.

![image](https://github.com/user-attachments/assets/1ccf7dd4-6dd7-4789-aed3-b06bf7b68766)
![image](https://github.com/user-attachments/assets/73d92fb0-557f-4817-9839-6de80d512e04)
![image](https://github.com/user-attachments/assets/b3c0dfd3-88ee-4080-a7f2-aab4807e71cc)
![image](https://github.com/user-attachments/assets/24a23937-89ff-4562-b318-65f7ff53d83f)

**Comment by luciaV86** [comment]
ok we can keep it as it is then

**Comment by syphax-bouazzouni** [comment]
Great thanks.
