### ISSUE TITLE
DOI minting error

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#133]
I have processed a DOI request
![image](https://github.com/user-attachments/assets/ee4c0348-3ec3-49e3-bd36-15b2e6c6db17)

but the link gives error
![image](https://github.com/user-attachments/assets/ab30ba5b-58ab-4ca7-9699-3bbc1b267c31)

**Comment by syphax-bouazzouni** [comment]
hello @martinaPulieri, this is fixed now, the issue was that we used a testing DataCite server for the dev server, now that I use the official Datacite server, it does work.  

But just for information, the DOI created does not redirect to EcoPortal but to the URI of the semantic artifact. For example, https://ecoportal.lifewatchdev.eu/ontologies/TRAITS_THES, generated doi is https://doi.org/10.48373/a2at-d828, and do redirect to https://kos.lifewatch.eu/thesauri/traits/ which is the URI of that resource.  **Is this the expected behavior?**

**Comment by martinaPulieri** [comment]
No, it should redirect the EcoPortal summary page of the resource

**Comment by syphax-bouazzouni** [comment]
> No, it should redirect the EcoPortal summary page of the resource

Done in a87a0edca4c7886226a4ed043af7e19d969ba082
Now all created DOIs redirected to Ecoportal not to the original URI of the resource.
