### ISSUE TITLE
Not findable resource from "Discover semantic resources" page

### ISSUE THREAD

**Issue by dadeex** [lifewatch-eric/ecoportal_web_ui#73]
I create this resource
https://ecoportal.lifewatchdev.eu/ontologies/INRAETHESTEST3
that is visible from search page but not in the "Discover semantic resources" 
<img width="1262" alt="image" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/59953068/b07f15b8-a8b5-48b2-aeef-efe9724bfea8">
<img width="572" alt="image" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/59953068/7be7fa9d-4725-4193-8db8-3ca4f31eff4e">

**Comment by syphax-bouazzouni** [comment]
It is because of the caching; sometimes you need to wait a little until the cache is refreshed (the cache expiry is a maximum of 1 hour).

Cache is required to make that page fast, but the inconvenience is that it is not always synced.

I am closing this issue and moving it to https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/698 to see if we can fix it in the future.
