### ISSUE TITLE
DOI Minting Process Fails with ArgumentError

### ISSUE THREAD

**Issue by Ramezani-07** [lifewatch-eric/ecoportal_web_ui#94]
Description: The DOI minting process is not functioning properly. Upon attempting to accept and process a DOI request via the admin tab, the following error message is encountered:

Error: "Problem processing Request 1729169330746 - ArgumentError: bad argument (expected URI object or URI string)"

Steps to Reproduce:

Navigate to the admin tab.
Attempt to accept and process a DOI request.
Observe the error message.
<img width="1439" alt="Screenshot 2024-10-18 at 13 25 13" src="https://github.com/user-attachments/assets/ae51ba6c-83ab-497e-b25b-94b9d1230529">

Expected Behavior: The system should process the DOI request without any errors and generate a DOI.

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/3762e8f6e040bdae2d1eba279df0e52635f1ecc7, the issue was that DOI requires a publisher and creators, so if not provided now we pass by default the portal name as publisher, and the current user name as creator.

![image](https://github.com/user-attachments/assets/acb3c9dc-b53f-434c-bc37-bee63ab43e96)
